export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS"
export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST"
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL"

export const QUESTION_DETAILS_SUCCESS = "QUESTION_DETAILS_SUCCESS"
export const QUESTION_DETAILS_REQUEST = "QUESTION_DETAILS_REQUEST"
export const QUESTION_DETAILS_FAIL = "QUESTION_DETAILS_FAIL"