export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_FAIL = 'USER_INFO_FAIL'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'  